//! Canonical manifest contract for tool metadata, risk flags, and planning policies.
const std = @import("std");

const types = @import("types.zig");
const aggregate = @import("aggregate.zig");
const groups_mod = @import("groups.zig");

/// Tooling helpers for manifest validation and catalog generation.
pub const tooling = @import("tooling.zig");
/// Renderer for compact tool catalog JSON.
pub const tool_catalog_render = @import("tool_catalog_render.zig");
/// Manifest version constants.
pub const version = @import("version.zig");

/// Stable tool group enum exposed to adapters and catalog renderers.
pub const ToolGroup = types.ToolGroup;
/// Risk flag set attached to each tool definition.
pub const ToolRisk = types.ToolRisk;
/// Static-analysis evidence tier for tools that report source facts.
pub const StaticAnalysisTier = types.StaticAnalysisTier;
/// File-scoped command planning metadata.
pub const FileCommandPlan = types.FileCommandPlan;
/// Exact command planning metadata.
pub const CommandPlan = types.CommandPlan;
/// ZLS request planning metadata.
pub const ZlsPlan = types.ZlsPlan;
/// Planning policy union used by manifest entries.
pub const PlanPolicy = types.PlanPolicy;
/// Canonical manifest definition shape.
pub const ToolDefinition = types.ToolDefinition;
/// Group metadata shape used by catalog rendering.
pub const GroupSpec = types.GroupSpec;

/// Stable enum of every manifest tool id.
pub const ToolId = aggregate.ToolId;
/// Compact metadata attached to one tool entry.
pub const ToolMeta = aggregate.ToolMeta;
/// Full aggregate entry tying a tool id to metadata.
pub const ToolEntry = aggregate.ToolEntry;
/// Ordered manifest definitions generated by the aggregate module.
pub const definitions = aggregate.definitions;
/// Group keyword metadata used by search and catalog output.
pub const group_specs = groups_mod.group_specs;
const group_keywords = buildGroupKeywords();

/// Ordered manifest entries indexed by `ToolId`.
pub const entries = aggregate.entries;
/// Tool specification slice used by adapter registration.
pub const specs = aggregate.specs;

/// Returns the registry entry for a tool id.
pub fn entryFor(id: ToolId) ToolEntry {
    return entries[@intFromEnum(id)];
}

/// Finds a tool by name and returns null when no registry entry matches.
pub fn find(name: []const u8) ?ToolMeta {
    for (entries) |entry| {
        if (std.mem.eql(u8, entry.name, name)) return entry.meta;
    }
    return null;
}

/// Finds a tool entry by name and returns null when absent.
pub fn findEntry(name: []const u8) ?ToolEntry {
    for (entries) |entry| {
        if (std.mem.eql(u8, entry.name, name)) return entry;
    }
    return null;
}

/// Returns the manifest group assigned to a tool id.
pub fn groupFor(id: ToolId) ToolGroup {
    return entryFor(id).group;
}

/// Returns the serialized manifest group name.
pub fn groupName(group: ToolGroup) []const u8 {
    return @tagName(group);
}

/// Returns search keywords associated with a manifest group.
pub fn groupKeywords(group: ToolGroup) []const []const u8 {
    return group_keywords[@intFromEnum(group)];
}

/// Returns the risk policy assigned to a tool id.
pub fn riskFor(id: ToolId) ToolRisk {
    return entryFor(id).risk;
}

/// Returns the planning policy assigned to a tool id.
pub fn planFor(id: ToolId) PlanPolicy {
    return entryFor(id).plan;
}

/// Returns the static-analysis evidence tier assigned to a tool id.
pub fn staticAnalysisTierFor(id: ToolId) ?StaticAnalysisTier {
    return entryFor(id).static_analysis_tier;
}

/// Returns an exact command plan when the tool is command-backed.
pub fn commandPlanFor(id: ToolId) ?CommandPlan {
    return switch (planFor(id)) {
        .exact_command => |plan| plan,
        else => null,
    };
}

/// Returns the serialized planning policy kind.
pub fn planKind(plan: PlanPolicy) []const u8 {
    return switch (plan) {
        .exact_command => "exact_command",
        .dynamic_command => "dynamic_command",
        .zls_request => "zls_request",
        .apply_gated_mutation => "apply_gated_mutation",
        .workspace_artifact => "workspace_artifact",
        .pure_analysis => "pure_analysis",
        .not_plannable => "not_plannable",
    };
}

/// Returns the serialized risk level implied by risk flags.
pub fn riskLevel(risk: ToolRisk) []const u8 {
    if (risk.writes_source or risk.executes_user_command) return "high";
    if (risk.executes_project_code or risk.writes_artifacts) return "medium";
    if (risk.mutates_lsp_state or risk.executes_backend) return "low";
    return "none";
}

/// Builds JSON risk flags and planner hints for one registered tool.
pub fn riskValue(allocator: std.mem.Allocator, spec: ToolMeta) !std.json.Value {
    const risk_value = riskFor(spec.id);
    var obj = std.json.ObjectMap.empty;
    errdefer obj.deinit(allocator);
    try obj.put(allocator, "level", .{ .string = riskLevel(risk_value) });
    try obj.put(allocator, "mcp_read_only_hint", .{ .bool = readOnlyHintFor(spec) });
    try obj.put(allocator, "writes_source", .{ .bool = risk_value.writes_source });
    try obj.put(allocator, "writes_artifacts", .{ .bool = risk_value.writes_artifacts });
    try obj.put(allocator, "writes_require_apply", .{ .bool = risk_value.writes_require_apply });
    try obj.put(allocator, "preview_by_default", .{ .bool = risk_value.preview_by_default });
    try obj.put(allocator, "mutates_lsp_state", .{ .bool = risk_value.mutates_lsp_state });
    try obj.put(allocator, "executes_project_code", .{ .bool = risk_value.executes_project_code });
    try obj.put(allocator, "executes_user_command", .{ .bool = risk_value.executes_user_command });
    try obj.put(allocator, "executes_backend", .{ .bool = risk_value.executes_backend });
    return .{ .object = obj };
}

/// Computes the external mutability hint from both declared read_only and risk capabilities.
pub fn readOnlyHintFor(spec: ToolMeta) bool {
    const risk_value = riskFor(spec.id);
    return spec.read_only and
        !risk_value.writes_source and
        !risk_value.writes_artifacts and
        !risk_value.mutates_lsp_state and
        !risk_value.executes_project_code and
        !risk_value.executes_user_command;
}

/// Returns whether the tool can be treated as idempotent by planners.
///
/// Policy: idempotent iff externally read-only. `readOnlyHintFor` already
/// requires all five capability flags (`writes_source`, `writes_artifacts`,
/// `mutates_lsp_state`, `executes_project_code`, `executes_user_command`) to be
/// clear, so re-ANDing them here never changed the result. The redundancy is
/// collapsed; the emitted `idempotentHint` value is unchanged for every tool. If
/// a read-only-but-non-idempotent operation ever needs to be expressed, this is
/// the single place to relax the equivalence.
pub fn idempotentHintFor(spec: ToolMeta) bool {
    return readOnlyHintFor(spec);
}

/// Returns whether the tool has destructive-risk markers.
///
/// Capability dominates the default-preview convenience: a tool that writes
/// source or executes project/user code is destructive even when it is
/// apply-gated, because the apply gate is a runtime guard, not a reason to tell
/// an agent the operation is only additive. Only after capability has been ruled
/// out does the apply-preview default suppress the destructive hint.
pub fn destructiveHintFor(spec: ToolMeta) bool {
    const risk_value = riskFor(spec.id);
    if (risk_value.writes_source or risk_value.executes_project_code or risk_value.executes_user_command) return true;
    if (risk_value.writes_require_apply and risk_value.preview_by_default) return false;
    return risk_value.writes_artifacts or risk_value.mutates_lsp_state or !spec.read_only;
}

/// Builds the group-keyword lookup table at comptime from group specs.
fn buildGroupKeywords() [std.meta.fields(ToolGroup).len][]const []const u8 {
    var result: [std.meta.fields(ToolGroup).len][]const []const u8 = undefined;
    inline for (group_specs) |spec| result[@intFromEnum(spec.group)] = spec.keywords;
    return result;
}

test {
    _ = @import("all_tests.zig");
}
