const types = @import("../types.zig");

const schema = types.schema;
const schemaWithHints = types.schemaWithHints;
const tool = types.tool;

/// Build a parser-backed workspace semantic index with declarations, imports, tests, and evidence-source metadata.
const static_plan = "Evidence-backed static workspace analysis; reads project files and reports source confidence without executing project code.";
/// Build a parser-backed workspace semantic index with declarations, imports, tests, and evidence-source metadata.
const lint_plan = "Backend-backed lint workflow whose exact argv depends on configured optional backend paths and runtime arguments.";
/// Build a parser-backed workspace semantic index with declarations, imports, tests, and evidence-source metadata.
const artifact_plan = "Preview-first workspace artifact export; writes only when apply=true and the output resolves inside the workspace.";

/// Build a parser-backed workspace semantic index with declarations, imports, tests, and evidence-source metadata.
pub const zig_semantic_index_build = tool(.{ .description = "Build a parser-backed workspace semantic index with declarations, imports, tests, and evidence-source metadata.", .input_schema = schema(&.{ .{ "refresh", "boolean", false }, .{ "limit", "integer", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .parser_backed });
/// Inspect the cached semantic index state, schema version, and refresh/hit counters.
pub const zig_semantic_index_status = tool(.{ .description = "Inspect the cached semantic index state, schema version, and refresh/hit counters.", .input_schema = schema(&.{}), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Refresh the parser-backed workspace semantic index and return the rebuilt index.
pub const zig_semantic_index_refresh = tool(.{ .description = "Refresh the parser-backed workspace semantic index and return the rebuilt index.", .input_schema = schema(&.{.{ "limit", "integer", false }}), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .parser_backed });
/// Query the semantic index for matching declarations, imports, tests, and files with evidence metadata.
pub const zig_semantic_query = tool(.{ .description = "Query the semantic index for matching declarations, imports, tests, and files with evidence metadata.", .input_schema = schema(&.{ .{ "query", "string", true }, .{ "kind", "string", false }, .{ "limit", "integer", false }, .{ "refresh", "boolean", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .parser_backed });
/// Find heuristic references to a symbol across workspace Zig files and report parser/source-scan evidence limits.
pub const zig_semantic_refs = tool(.{ .description = "Find heuristic references to a symbol across workspace Zig files and report parser/source-scan evidence limits.", .input_schema = schema(&.{ .{ "symbol", "string", true }, .{ "limit", "integer", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Find semantic-index declarations for a symbol with source locations, signatures, and confidence evidence.
pub const zig_semantic_decl = tool(.{ .description = "Find semantic-index declarations for a symbol with source locations, signatures, and confidence evidence.", .input_schema = schema(&.{ .{ "symbol", "string", true }, .{ "limit", "integer", false }, .{ "refresh", "boolean", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .parser_backed });
/// Find likely call sites for a symbol using workspace source scans with explicit heuristic limitations.
pub const zig_semantic_callers = tool(.{ .description = "Find likely call sites for a symbol using workspace source scans with explicit heuristic limitations.", .input_schema = schema(&.{ .{ "symbol", "string", true }, .{ "limit", "integer", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Fuse semantic-index, source-scan, ZLint, and zwanzig evidence into a confidence-ranked static answer.
pub const zig_static_fusion = tool(.{ .description = "Fuse semantic-index, source-scan, ZLint, and zwanzig evidence into a confidence-ranked static answer.", .input_schema = schema(&.{ .{ "query", "string", true }, .{ "zlint_findings", "string", false }, .{ "zwanzig_findings", "string", false }, .{ "limit", "integer", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Export the semantic index as a stable zigar code-index JSON artifact, previewing unless apply=true.
pub const zig_code_index_export = tool(.{ .description = "Export the semantic index as a stable zigar code-index JSON artifact, previewing unless apply=true.", .input_schema = schema(&.{ .{ "output", "string", false }, .{ "apply", "boolean", false }, .{ "limit", "integer", false }, .{ "refresh", "boolean", false } }), .read_only = true, .group = .static_analysis, .risk = .{ .writes_artifacts = true, .writes_require_apply = true, .preview_by_default = true }, .plan = .{ .workspace_artifact = artifact_plan }, .static_analysis_tier = .parser_backed });
/// Export the semantic index as a compact SCIP-like JSON artifact, previewing unless apply=true.
pub const zig_scip_export = tool(.{ .description = "Export the semantic index as a compact SCIP-like JSON artifact, previewing unless apply=true.", .input_schema = schema(&.{ .{ "output", "string", false }, .{ "apply", "boolean", false }, .{ "limit", "integer", false }, .{ "refresh", "boolean", false } }), .read_only = true, .group = .static_analysis, .risk = .{ .writes_artifacts = true, .writes_require_apply = true, .preview_by_default = true }, .plan = .{ .workspace_artifact = artifact_plan }, .static_analysis_tier = .parser_backed });

/// Run optional ZLint and return normalized diagnostics with rule, severity, location, and source evidence.
pub const zig_zlint = tool(.{ .description = "Run optional ZLint and return normalized diagnostics with rule, severity, location, and source evidence.", .input_schema = schema(&.{ .{ "path", "string", false }, .{ "config", "string", false }, .{ "rules", "string", false }, .{ "args", "string", false }, .{ "timeout_ms", "integer", false } }), .read_only = true, .group = .static_analysis, .risk = .{ .executes_backend = true }, .plan = .{ .dynamic_command = lint_plan }, .static_analysis_tier = .zlint_backed });
/// Run optional ZLint and convert normalized diagnostics into SARIF 2.
pub const zig_zlint_sarif = tool(.{ .description = "Run optional ZLint and convert normalized diagnostics into SARIF 2.1.0 JSON.", .input_schema = schema(&.{ .{ "path", "string", false }, .{ "config", "string", false }, .{ "rules", "string", false }, .{ "args", "string", false }, .{ "timeout_ms", "integer", false } }), .read_only = true, .group = .static_analysis, .risk = .{ .executes_backend = true }, .plan = .{ .dynamic_command = lint_plan }, .static_analysis_tier = .zlint_backed });
/// Run optional ZLint rule discovery and return normalized rule metadata with configuration hints.
pub const zig_zlint_rules = tool(.{ .description = "Run optional ZLint rule discovery and return normalized rule metadata with configuration hints.", .input_schema = schema(&.{.{ "timeout_ms", "integer", false }}), .read_only = true, .group = .static_analysis, .risk = .{ .executes_backend = true }, .plan = .{ .dynamic_command = lint_plan }, .static_analysis_tier = .zlint_backed });
/// Preview or apply ZLint automatic fixes under an explicit apply gate.
pub const zig_zlint_fix = tool(.{ .description = "Preview or apply ZLint automatic fixes under an explicit apply gate.", .input_schema = schema(&.{ .{ "path", "string", false }, .{ "config", "string", false }, .{ "rules", "string", false }, .{ "args", "string", false }, .{ "dangerous", "boolean", false }, .{ "apply", "boolean", false }, .{ "timeout_ms", "integer", false } }), .read_only = false, .group = .static_analysis, .risk = .{ .writes_source = true, .writes_require_apply = true, .preview_by_default = true, .executes_backend = true }, .plan = .{ .apply_gated_mutation = "Preview-first ZLint source mutation; runs --fix or --fix-dangerously only when apply=true and the path resolves inside the workspace." }, .static_analysis_tier = .zlint_backed });
/// Compare normalized ZLint and zwanzig findings into consensus, disagreement, and backend-only buckets.
pub const zig_lint_compare = tool(.{ .description = "Compare normalized ZLint and zwanzig findings into consensus, disagreement, and backend-only buckets.", .input_schema = schemaWithHints(&.{ .{ "zlint_findings", "string", false }, .{ "zwanzig_findings", "string", false } }, &.{ .{ .field_name = "zlint_findings", .hint = .{ .description = "JSON from zig_zlint, a findings array, or a raw ZLint object." } }, .{ .field_name = "zwanzig_findings", .hint = .{ .description = "JSON from zig_lint, a findings array, or a raw zwanzig object." } } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Return lint gate profiles with severity thresholds, backend requirements, and adoption guidance.
pub const zig_lint_profile = tool(.{ .description = "Return lint gate profiles with severity thresholds, backend requirements, and adoption guidance.", .input_schema = schema(&.{.{ "profile", "string", false }}), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Evaluate normalized lint findings against a named gate profile and report blocking findings.
pub const zig_lint_gate = tool(.{ .description = "Evaluate normalized lint findings against a named gate profile and report blocking findings.", .input_schema = schema(&.{ .{ "findings", "string", true }, .{ "profile", "string", false }, .{ "max_warnings", "integer", false }, .{ "allow_warnings", "boolean", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Group normalized lint findings into safe, risky, and manual buckets and point apply-capable cases at zig_zlint_fix.
pub const zig_lint_fix_plan = tool(.{ .description = "Group normalized lint findings into safe, risky, and manual buckets and point apply-capable cases at zig_zlint_fix.", .input_schema = schema(&.{.{ "findings", "string", true }}), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Compare lint findings with a baseline and optionally write a workspace-local baseline artifact when apply=true.
pub const zig_lint_baseline = tool(.{ .description = "Compare lint findings with a baseline and optionally write a workspace-local baseline artifact when apply=true.", .input_schema = schema(&.{ .{ "findings", "string", true }, .{ "baseline", "string", false }, .{ "output", "string", false }, .{ "apply", "boolean", false } }), .read_only = true, .group = .static_analysis, .risk = .{ .writes_artifacts = true, .writes_require_apply = true, .preview_by_default = true }, .plan = .{ .workspace_artifact = artifact_plan }, .static_analysis_tier = .advisory_orientation });
/// Apply lint suppression metadata to normalized findings and report suppressed, active, and stale entries.
pub const zig_lint_suppressions = tool(.{ .description = "Apply lint suppression metadata to normalized findings and report suppressed, active, and stale entries.", .input_schema = schema(&.{ .{ "findings", "string", true }, .{ "suppressions", "string", false } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
/// Compare before/after lint findings and report new, resolved, persistent, and severity-delta trend signals.
pub const zig_lint_trend = tool(.{ .description = "Compare before/after lint findings and report new, resolved, persistent, and severity-delta trend signals.", .input_schema = schema(&.{ .{ "before", "string", true }, .{ "after", "string", true } }), .read_only = true, .group = .static_analysis, .plan = .{ .pure_analysis = static_plan }, .static_analysis_tier = .advisory_orientation });
