import assert from "node:assert/strict";
import test from "node:test";
import {
  ChecksumError,
  checksumForArchive,
  parseChecksums,
  verifySha256,
} from "../src/checksums";

test("parses checksum file entries", () => {
  const entries = parseChecksums([
    "# generated by release",
    "A".repeat(64) + "  zigars-x86_64-linux-musl.tar.gz",
    "b".repeat(64) + "  *zigars-aarch64-macos.tar.gz",
    "",
  ].join("\n"));

  assert.equal(entries.get("zigars-x86_64-linux-musl.tar.gz"), "a".repeat(64));
  assert.equal(entries.get("zigars-aarch64-macos.tar.gz"), "b".repeat(64));
});

test("rejects malformed checksum lines", () => {
  assert.throws(() => parseChecksums("not-a-checksum  archive.tar.gz\n"), {
    name: "ChecksumError",
    code: "ERR_ZIGARS_CHECKSUM_PARSE",
  });
});

test("rejects missing archive checksum entries", () => {
  assert.throws(() => checksumForArchive(new Map(), "zigars-x86_64-linux-musl.tar.gz"), {
    name: "ChecksumError",
    code: "ERR_ZIGARS_CHECKSUM_MISSING",
  });
});

test("verifies archive sha256 and rejects mismatches", () => {
  assert.equal(
    verifySha256(Buffer.from("archive"), "0EB3E36BFB24DCD9BB1D1BECE1531216B59539A8FDE17EE80224AF0653C92AA3", "archive.tar.gz"),
    "0eb3e36bfb24dcd9bb1d1bece1531216b59539a8fde17ee80224af0653c92aa3",
  );

  assert.throws(
    () => verifySha256(Buffer.from("archive"), "0".repeat(64), "archive.tar.gz"),
    (error) => {
      const checksumError = error as ChecksumError;
      assert.equal(checksumError instanceof ChecksumError, true);
      assert.equal(checksumError.code, "ERR_ZIGARS_CHECKSUM_MISMATCH");
      assert.match(checksumError.message, /Checksum mismatch/);
      return true;
    },
  );

  assert.throws(() => verifySha256(Buffer.from("archive"), "not-a-sha256", "archive.tar.gz"), {
    name: "ChecksumError",
    code: "ERR_ZIGARS_CHECKSUM_MISMATCH",
  });
});
