//! Generator for `docs/tool-index.generated.md`.
//!
//! Reads `src/manifest/tool_catalog.json` via the `catalog_render` helper,
//! then renders a Markdown document with groups, common intents, compact
//! argument hints, planning support, and static-analysis capability tiers.
//! The output is checked for staleness by `zig build docs-check`; run
//! `zig build tool-index` to regenerate.
const std = @import("std");

const Io = std.Io;
const Allocator = std.mem.Allocator;
const JsonValue = std.json.Value;
const zigars = @import("zigars");
const catalog_mod = zigars.manifest.tool_catalog_render;
const manifest = zigars.manifest;

/// Reads a repository-relative file with a byte limit.
fn readFileAlloc(allocator: Allocator, io: Io, path: []const u8, limit: usize) ![]u8 {
    return Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(limit));
}

/// Writes generated bytes to a repository-relative file.
fn writeFile(io: Io, path: []const u8, bytes: []const u8) !void {
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = bytes });
}

/// Writes a formatted diagnostic to stderr.
fn stderrPrint(io: Io, comptime fmt: []const u8, args: anytype) !void {
    var buffer: [4096]u8 = undefined;
    var writer = Io.File.stderr().writer(io, &buffer);
    try writer.interface.print(fmt, args);
    try writer.interface.flush();
}

/// Generates `docs/tool-index.generated.md` from the live catalog JSON.
/// With `--check`, compares the rendered output to the file on disk and
/// returns `error.StaleGeneratedFile` when they differ; without it, writes
/// the rendered content to disk. The file must be committed and kept current.
pub fn generate(allocator: Allocator, io: Io, args: []const []const u8) !void {
    var check = false;
    for (args) |arg| {
        if (std.mem.eql(u8, arg, "--check")) {
            check = true;
        } else {
            return error.InvalidArguments;
        }
    }

    const output_path = "docs/tool-index.generated.md";
    const parsed = try catalog_mod.parsed(allocator);
    defer parsed.deinit();

    const rendered = try renderToolIndex(allocator, parsed.value);
    defer allocator.free(rendered);

    if (check) {
        const existing_owned = readFileAlloc(allocator, io, output_path, 16 * 1024 * 1024) catch null;
        defer if (existing_owned) |existing| allocator.free(existing);
        const existing = existing_owned orelse "";
        if (!std.mem.eql(u8, existing, rendered)) {
            try stderrPrint(io, "{s} is stale; run `zig build tool-index`\n", .{output_path});
            return error.StaleGeneratedFile;
        }
        return;
    }

    try writeFile(io, output_path, rendered);
}

/// Renders the full Markdown document from a parsed catalog JSON value.
/// The caller owns the returned slice and must free it.
fn renderToolIndex(allocator: Allocator, catalog: JsonValue) ![]u8 {
    const obj = catalog.object;
    var out: Io.Writer.Allocating = .init(allocator);
    errdefer out.deinit();

    try out.writer.print(
        \\# Zigars Tool Index
        \\
        \\<!-- Generated by zigars-tools generate-tool-index. Do not edit by hand. -->
        \\
        \\Schema version: `{d}`
        \\
        \\{s}
        \\
        \\## Groups
        \\
        \\
    , .{
        obj.get("schema_version").?.integer,
        obj.get("purpose").?.string,
    });

    for (obj.get("groups").?.array.items) |group_value| {
        const group = group_value.object;
        try out.writer.print("### {s}\n\nTools: ", .{group.get("name").?.string});
        try renderBacktickList(&out.writer, group.get("tools").?.array.items);
        try out.writer.writeAll("\n\nKeywords: ");
        try renderBacktickList(&out.writer, group.get("keywords").?.array.items);
        try out.writer.writeAll("\n\n");
    }

    try out.writer.writeAll("## Common Intents\n\n");
    for (obj.get("common_intents").?.array.items) |intent_value| {
        const item = intent_value.object;
        try out.writer.print("- {s}: prefer `{s}`\n", .{
            item.get("intent").?.string,
            item.get("prefer").?.string,
        });
    }
    try out.writer.writeAll("\n## Compact Argument Hints\n\n");

    var keys: std.ArrayList([]const u8) = .empty;
    defer keys.deinit(allocator);
    for (manifest.specs) |spec| {
        if (spec.input_schema.fields.len > 0) try keys.append(allocator, spec.name);
    }
    std.mem.sort([]const u8, keys.items, {}, stringLessThan);

    for (keys.items) |tool_name| {
        const spec = manifest.find(tool_name).?;
        try out.writer.print("- `{s}`: ", .{tool_name});
        var wrote_fragment = false;
        if (hasSchemaFields(spec, true)) {
            try out.writer.writeAll("required ");
            try renderArgumentFields(&out.writer, spec, true);
            wrote_fragment = true;
        }
        if (hasSchemaFields(spec, false)) {
            if (wrote_fragment) try out.writer.writeAll("; ");
            try out.writer.writeAll("optional ");
            try renderArgumentFields(&out.writer, spec, false);
        }
        try out.writer.writeAll("\n");
    }

    try out.writer.writeAll("\n## Planning Support\n\n");
    var plan_keys: std.ArrayList([]const u8) = .empty;
    defer plan_keys.deinit(allocator);
    for (manifest.entries) |entry| try plan_keys.append(allocator, entry.name);
    std.mem.sort([]const u8, plan_keys.items, {}, stringLessThan);

    for (plan_keys.items) |tool_name| {
        const entry = manifest.findEntry(tool_name).?;
        try out.writer.print("- `{s}`: `{s}`", .{ tool_name, manifest.planKind(entry.plan) });
        switch (entry.plan) {
            .exact_command => try out.writer.writeAll(" exact argv"),
            .dynamic_command => try out.writer.writeAll(" runtime-dependent backend plan"),
            .zls_request => |plan| try out.writer.print(" `{s}`", .{plan.method}),
            .apply_gated_mutation => try out.writer.writeAll(" preview/apply mutation"),
            .workspace_artifact => try out.writer.writeAll(" explicit workspace artifact"),
            .pure_analysis => try out.writer.writeAll(" read-only analysis"),
            .not_plannable => try out.writer.writeAll(" unsupported"),
        }
        try out.writer.writeAll("\n");
    }

    try out.writer.writeAll("\n## Static Analysis Capability Tiers\n\n");
    const static_contracts = obj.get("registry_static_analysis_contracts").?.object;
    var static_keys: std.ArrayList([]const u8) = .empty;
    defer static_keys.deinit(allocator);
    for (manifest.entries) |entry| {
        if (entry.static_analysis_tier != null) try static_keys.append(allocator, entry.name);
    }
    std.mem.sort([]const u8, static_keys.items, {}, stringLessThan);
    for (static_keys.items) |tool_name| {
        const contract = static_contracts.get(tool_name).?.object;
        try out.writer.print("- `{s}`: tier `{s}`, confidence `{s}`, class `{s}`, kind `{s}`; cross-check `{s}`\n", .{
            tool_name,
            contract.get("capability_tier").?.string,
            contract.get("confidence").?.string,
            contract.get("confidence_class").?.string,
            contract.get("analysis_kind").?.string,
            contract.get("recommended_cross_check").?.string,
        });
    }

    try out.writer.print("\n{s}\n", .{obj.get("tools_list_schema_note").?.string});
    return try out.toOwnedSlice();
}

/// Sort predicate for deterministic tool-name ordering.
fn stringLessThan(_: void, lhs: []const u8, rhs: []const u8) bool {
    return std.mem.order(u8, lhs, rhs) == .lt;
}

/// Renders a comma-separated list of strings as Markdown code spans.
fn renderBacktickList(writer: *Io.Writer, items: []const JsonValue) !void {
    for (items, 0..) |item, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{item.string});
    }
}

/// Reports whether a tool schema has required or optional fields.
fn hasSchemaFields(spec: manifest.ToolMeta, required: bool) bool {
    for (spec.input_schema.fields) |field| {
        if (field[2] == required) return true;
    }
    return false;
}

/// Renders required or optional schema fields as compact argument hints.
fn renderArgumentFields(writer: *Io.Writer, spec: manifest.ToolMeta, required: bool) !void {
    var i: usize = 0;
    for (spec.input_schema.fields) |field| {
        if (field[2] != required) continue;
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}: {s}`", .{ field[0], field[1] });
        i += 1;
    }
}

test "tool index renderer exposes generate entrypoint" {
    try std.testing.expect(@hasDecl(@This(), "generate"));
}
