//! Compile-time mapping from manifest tool IDs to adapter modules and exported handler names.
const manifest = @import("../../manifest/mod.zig");

/// Adapter module buckets used by compile-time dispatch in handlers.zig.
pub const HandlerModule = enum {
    discovery,
    agent,
    artifacts,
    core,
    edit_zls,
    edit_zls_diagnostics,
    docs,
    static_analysis,
    ci,
    observability,
    zwanzig,
    profiling,
    trust,
    result_shape,
    release_drift,
    environment_profiles,
    runtime_ux,
    validation_workflows,
    transactional_editing,
    phase6,
    performance,
    diagnostics,
    adoption,
};

/// Pair of adapter module and exported function name for a manifest tool id.
pub const HandlerRef = struct {
    module: HandlerModule,
    name: []const u8,
};

/// Resolves a manifest ToolId to the adapter function that implements it.
pub fn handlerFor(id: manifest.ToolId) HandlerRef {
    // This table is the manifest-to-adapter boundary: every tool id maps to the
    // concrete adapter module and exported handler name used by registration.
    return switch (id) {
        .zigars_adoption_pack => .{ .module = .adoption, .name = "zigarsAdoptionPack" },
        .zigars_client_config_generate => .{ .module = .adoption, .name = "zigarsClientConfigGenerate" },
        .zigars_smoke_plan => .{ .module = .adoption, .name = "zigarsSmokePlan" },
        .zigars_conformance_report => .{ .module = .adoption, .name = "zigarsConformanceReport" },
        .zigars_context_pack => .{ .module = .agent, .name = "zigarsContextPack" },
        .zigars_next_action => .{ .module = .agent, .name = "zigarsNextAction" },
        .zigars_agent_guide => .{ .module = .agent, .name = "zigarsAgentGuide" },
        .zigars_validate_patch => .{ .module = .agent, .name = "zigarsValidatePatch" },
        .zigars_failure_fusion => .{ .module = .agent, .name = "zigarsFailureFusion" },
        .zigars_impact => .{ .module = .agent, .name = "zigarsImpact" },
        .zigars_project_profile => .{ .module = .agent, .name = "zigarsProjectProfile" },
        .zigars_patch_guard => .{ .module = .agent, .name = "zigarsPatchGuard" },
        .zig_ci_annotations => .{ .module = .ci, .name = "zigCiAnnotations" },
        .zig_junit => .{ .module = .ci, .name = "zigJunit" },
        .zig_matrix_check => .{ .module = .ci, .name = "zigMatrixCheck" },
        .zig_version => .{ .module = .core, .name = "zigVersion" },
        .zig_env => .{ .module = .core, .name = "zigEnv" },
        .zig_targets => .{ .module = .core, .name = "zigTargets" },
        .zig_build => .{ .module = .core, .name = "zigBuild" },
        .zig_test => .{ .module = .core, .name = "zigTest" },
        .zig_check => .{ .module = .core, .name = "zigCheck" },
        .zig_compile_error_index => .{ .module = .core, .name = "zigCompileErrorIndex" },
        .zig_explain_errors => .{ .module = .core, .name = "zigExplainErrors" },
        .zig_translate_c => .{ .module = .core, .name = "zigTranslateC" },
        .zig_debug_plan => .{ .module = .diagnostics, .name = "zigDebugPlan" },
        .zig_lldb_backtrace => .{ .module = .diagnostics, .name = "zigLldbBacktrace" },
        .zig_core_inspect => .{ .module = .diagnostics, .name = "zigCoreInspect" },
        .zig_debug_frame_summary => .{ .module = .diagnostics, .name = "zigDebugFrameSummary" },
        .zig_sanitizer_fusion => .{ .module = .diagnostics, .name = "zigSanitizerFusion" },
        .zig_panic_trace_analyze => .{ .module = .diagnostics, .name = "zigPanicTraceAnalyze" },
        .zig_crash_repro_plan => .{ .module = .diagnostics, .name = "zigCrashReproPlan" },
        .zig_heaptrack_run => .{ .module = .diagnostics, .name = "zigHeaptrackRun" },
        .zig_heaptrack_summary => .{ .module = .diagnostics, .name = "zigHeaptrackSummary" },
        .zig_valgrind_memcheck => .{ .module = .diagnostics, .name = "zigValgrindMemcheck" },
        .zig_callgrind_report => .{ .module = .diagnostics, .name = "zigCallgrindReport" },
        .zig_fuzz_plan => .{ .module = .diagnostics, .name = "zigFuzzPlan" },
        .zig_afl_run => .{ .module = .diagnostics, .name = "zigAflRun" },
        .zig_libfuzzer_run => .{ .module = .diagnostics, .name = "zigLibfuzzerRun" },
        .zig_fuzz_crash_minimize => .{ .module = .diagnostics, .name = "zigFuzzCrashMinimize" },
        .zig_fuzz_corpus_summary => .{ .module = .diagnostics, .name = "zigFuzzCorpusSummary" },
        .zig_binary_size => .{ .module = .diagnostics, .name = "zigBinarySize" },
        .zig_binary_size_diff => .{ .module = .diagnostics, .name = "zigBinarySizeDiff" },
        .zig_objdump_summary => .{ .module = .diagnostics, .name = "zigObjdumpSummary" },
        .zig_dwarfdump_check => .{ .module = .diagnostics, .name = "zigDwarfdumpCheck" },
        .zig_symbolize => .{ .module = .diagnostics, .name = "zigSymbolize" },
        .zig_qemu_test => .{ .module = .diagnostics, .name = "zigQemuTest" },
        .zig_cross_smoke => .{ .module = .diagnostics, .name = "zigCrossSmoke" },
        .zig_target_runtime_plan => .{ .module = .diagnostics, .name = "zigTargetRuntimePlan" },
        .zig_embedded_detect => .{ .module = .diagnostics, .name = "zigEmbeddedDetect" },
        .zig_microzig_plan => .{ .module = .diagnostics, .name = "zigMicrozigPlan" },
        .zig_board_profile => .{ .module = .diagnostics, .name = "zigBoardProfile" },
        .zig_flash_plan => .{ .module = .diagnostics, .name = "zigFlashPlan" },
        .zigars_capabilities => .{ .module = .discovery, .name = "zigarsCapabilities" },
        // Alias: the tool-index id reuses the capabilities handler intentionally.
        .zigars_tool_index => .{ .module = .discovery, .name = "zigarsCapabilities" },
        .zigars_schema => .{ .module = .discovery, .name = "zigarsSchema" },
        .zigars_backend_catalog => .{ .module = .discovery, .name = "zigarsBackendCatalog" },
        .zigars_doctor => .{ .module = .discovery, .name = "zigarsDoctor" },
        .zigars_workspace_info => .{ .module = .discovery, .name = "workspaceInfo" },
        .zigars_metrics => .{ .module = .discovery, .name = "zigarsMetrics" },
        .zigars_http_status => .{ .module = .discovery, .name = "zigarsHttpStatus" },
        .zig_command_plan => .{ .module = .discovery, .name = "zigCommandPlan" },
        .zig_tool_plan => .{ .module = .discovery, .name = "zigToolPlan" },
        .zig_toolchain_resolve => .{ .module = .discovery, .name = "zigToolchainResolve" },
        .zig_builtin_list => .{ .module = .docs, .name = "zigBuiltinList" },
        .zig_builtin_list_json => .{ .module = .docs, .name = "zigBuiltinListJson" },
        .zig_builtin_doc => .{ .module = .docs, .name = "zigBuiltinDoc" },
        .zig_builtin_doc_json => .{ .module = .docs, .name = "zigBuiltinDocJson" },
        .zig_std_search => .{ .module = .docs, .name = "zigStdSearch" },
        .zig_std_search_json => .{ .module = .docs, .name = "zigStdSearchJson" },
        .zig_std_item => .{ .module = .docs, .name = "zigStdItem" },
        .zig_std_item_json => .{ .module = .docs, .name = "zigStdItemJson" },
        .zig_lang_ref_search => .{ .module = .docs, .name = "zigLangRefSearch" },
        .zig_lang_ref_search_json => .{ .module = .docs, .name = "zigLangRefSearchJson" },
        .zigars_setup_guidance => .{ .module = .environment_profiles, .name = "zigarsSetupGuidance" },
        .zigars_profile_guidance => .{ .module = .environment_profiles, .name = "zigarsProfileGuidance" },
        .zigars_backend_guidance => .{ .module = .environment_profiles, .name = "zigarsBackendGuidance" },
        .zigars_project_profile_v2 => .{ .module = .environment_profiles, .name = "zigarsProjectProfileV2" },
        .zigars_profile_validate => .{ .module = .environment_profiles, .name = "zigarsProfileValidate" },
        .zigars_profile_read => .{ .module = .environment_profiles, .name = "zigarsProfileRead" },
        .zigars_profile_bootstrap => .{ .module = .environment_profiles, .name = "zigarsProfileBootstrap" },
        .zigars_profile_import => .{ .module = .environment_profiles, .name = "zigarsProfileImport" },
        .zigars_profile_diff => .{ .module = .environment_profiles, .name = "zigarsProfileDiff" },
        .zigars_env_pack => .{ .module = .environment_profiles, .name = "zigarsEnvPack" },
        .zigars_env_export => .{ .module = .environment_profiles, .name = "zigarsEnvExport" },
        .zigars_zvm_probe => .{ .module = .environment_profiles, .name = "zigarsZvmProbe" },
        .zigars_zvm_install_plan => .{ .module = .environment_profiles, .name = "zigarsZvmInstallPlan" },
        .zigars_zvm_switch_plan => .{ .module = .environment_profiles, .name = "zigarsZvmSwitchPlan" },
        .zig_zls_match_check => .{ .module = .environment_profiles, .name = "zigZlsMatchCheck" },
        .zig_toolchain_pin => .{ .module = .environment_profiles, .name = "zigToolchainPin" },
        .zig_toolchain_pin_check => .{ .module = .environment_profiles, .name = "zigToolchainPinCheck" },
        .zigars_backend_install_plan => .{ .module = .environment_profiles, .name = "zigarsBackendInstallPlan" },
        .zigars_backend_verify => .{ .module = .environment_profiles, .name = "zigarsBackendVerify" },
        .zigars_dev_env_generate => .{ .module = .environment_profiles, .name = "zigarsDevEnvGenerate" },
        .zigars_backend_conformance => .{ .module = .environment_profiles, .name = "zigarsBackendConformance" },
        .zigars_backend_evidence_pack => .{ .module = .environment_profiles, .name = "zigarsBackendEvidencePack" },
        .zig_format => .{ .module = .edit_zls, .name = "zigFormat" },
        .zig_format_check => .{ .module = .edit_zls, .name = "zigFormatCheck" },
        .zig_patch_preview => .{ .module = .edit_zls, .name = "zigPatchPreview" },
        .zig_rename => .{ .module = .edit_zls, .name = "zigRename" },
        .zig_code_actions => .{ .module = .edit_zls, .name = "zigCodeActions" },
        .zig_code_action_apply => .{ .module = .edit_zls, .name = "zigCodeActionApply" },
        .zigars_artifact_index => .{ .module = .artifacts, .name = "zigarsArtifactIndex" },
        .zigars_artifact_read => .{ .module = .artifacts, .name = "zigarsArtifactRead" },
        .zigars_session_view => .{ .module = .artifacts, .name = "zigarsSessionView" },
        .zigars_artifact_prune => .{ .module = .artifacts, .name = "zigarsArtifactPrune" },
        .zigars_metrics_v2 => .{ .module = .observability, .name = "zigarsMetricsV2" },
        .zigars_backend_health_history => .{ .module = .observability, .name = "zigarsBackendHealthHistory" },
        .zigars_zls_timeline => .{ .module = .observability, .name = "zigarsZlsTimeline" },
        .zigars_tool_latency => .{ .module = .observability, .name = "zigarsToolLatency" },
        .zigars_trust_report => .{ .module = .trust, .name = "zigarsTrustReport" },
        .zigars_command_provenance => .{ .module = .trust, .name = "zigarsCommandProvenance" },
        .zigars_risk_audit => .{ .module = .trust, .name = "zigarsRiskAudit" },
        .zigars_clean_tree_gate => .{ .module = .trust, .name = "zigarsCleanTreeGate" },
        .zigars_result_shape => .{ .module = .result_shape, .name = "zigarsResultShape" },
        .zigars_output_budget_plan => .{ .module = .result_shape, .name = "zigarsOutputBudgetPlan" },
        .zigars_docs_drift_check => .{ .module = .release_drift, .name = "zigarsDocsDriftCheck" },
        .zigars_release_claim_check => .{ .module = .release_drift, .name = "zigarsReleaseClaimCheck" },
        .zigars_tool_index_check => .{ .module = .release_drift, .name = "zigarsToolIndexCheck" },
        .zig_coverage_run => .{ .module = .performance, .name = "zigCoverageRun" },
        .zig_coverage_map => .{ .module = .performance, .name = "zigCoverageMap" },
        .zig_coverage_merge => .{ .module = .performance, .name = "zigCoverageMerge" },
        .zig_coverage_diff => .{ .module = .performance, .name = "zigCoverageDiff" },
        .zig_coverage_baseline => .{ .module = .performance, .name = "zigCoverageBaseline" },
        .zig_coverage_budget_check => .{ .module = .performance, .name = "zigCoverageBudgetCheck" },
        .zig_bench_discover => .{ .module = .performance, .name = "zigBenchDiscover" },
        .zig_bench_run => .{ .module = .performance, .name = "zigBenchRun" },
        .zig_bench_baseline => .{ .module = .performance, .name = "zigBenchBaseline" },
        .zig_benchmark_history => .{ .module = .performance, .name = "zigBenchmarkHistory" },
        .zig_bench_compare => .{ .module = .performance, .name = "zigBenchCompare" },
        .zig_bench_regression_gate => .{ .module = .performance, .name = "zigBenchRegressionGate" },
        .zig_perf_budget_check => .{ .module = .performance, .name = "zigPerfBudgetCheck" },
        .zig_profile_regression => .{ .module = .performance, .name = "zigProfileRegression" },
        .zig_samply_record => .{ .module = .performance, .name = "zigSamplyRecord" },
        .zig_samply_summary => .{ .module = .performance, .name = "zigSamplySummary" },
        .zig_samply_import => .{ .module = .performance, .name = "zigSamplyImport" },
        .zig_samply_artifact => .{ .module = .performance, .name = "zigSamplyArtifact" },
        .zig_profile_open => .{ .module = .performance, .name = "zigProfileOpen" },
        .zig_tracy_plan => .{ .module = .performance, .name = "zigTracyPlan" },
        .zig_tracy_probe => .{ .module = .performance, .name = "zigTracyProbe" },
        .zig_tracy_capture => .{ .module = .performance, .name = "zigTracyCapture" },
        .zig_tracy_artifacts => .{ .module = .performance, .name = "zigTracyArtifacts" },
        .zig_tracy_hints => .{ .module = .performance, .name = "zigTracyHints" },
        .zig_perf_evidence_pack => .{ .module = .performance, .name = "zigPerfEvidencePack" },
        .zig_ci_ingest => .{ .module = .phase6, .name = "zigCiIngest" },
        .zig_ci_repro_plan => .{ .module = .phase6, .name = "zigCiReproPlan" },
        .zig_ci_failure_map => .{ .module = .phase6, .name = "zigCiFailureMap" },
        .zig_release_plan => .{ .module = .phase6, .name = "zigReleasePlan" },
        .zig_semver_suggest => .{ .module = .phase6, .name = "zigSemverSuggest" },
        .zig_release_notes_draft => .{ .module = .phase6, .name = "zigReleaseNotesDraft" },
        .zig_release_evidence_pack => .{ .module = .phase6, .name = "zigReleaseEvidencePack" },
        .zig_api_baseline_init => .{ .module = .phase6, .name = "zigApiBaselineInit" },
        .zig_api_check => .{ .module = .phase6, .name = "zigApiCheck" },
        .zig_api_diff_baseline => .{ .module = .phase6, .name = "zigApiDiffBaseline" },
        .zig_api_docs_diff => .{ .module = .phase6, .name = "zigApiDocsDiff" },
        .zig_docs_index_build => .{ .module = .phase6, .name = "zigDocsIndexBuild" },
        .zig_docs_query => .{ .module = .phase6, .name = "zigDocsQuery" },
        .zig_std_signature => .{ .module = .phase6, .name = "zigStdSignature" },
        .zig_langref_item => .{ .module = .phase6, .name = "zigLangrefItem" },
        .zig_autodoc_ingest => .{ .module = .phase6, .name = "zigAutodocIngest" },
        .zig_project_docs_query => .{ .module = .phase6, .name = "zigProjectDocsQuery" },
        .zig_doc_example_check => .{ .module = .phase6, .name = "zigDocExampleCheck" },
        .zig_snippet_check => .{ .module = .phase6, .name = "zigSnippetCheck" },
        .zig_readme_command_check => .{ .module = .phase6, .name = "zigReadmeCommandCheck" },
        .zig_dependency_update_plan => .{ .module = .phase6, .name = "zigDependencyUpdatePlan" },
        .zig_dependency_fetch_check => .{ .module = .phase6, .name = "zigDependencyFetchCheck" },
        .zig_dependency_lock_audit => .{ .module = .phase6, .name = "zigDependencyLockAudit" },
        .zig_dependency_impact => .{ .module = .phase6, .name = "zigDependencyImpact" },
        .zig_sbom => .{ .module = .phase6, .name = "zigSbom" },
        .zig_zat_scan => .{ .module = .phase6, .name = "zigZatScan" },
        .zig_osv_scan => .{ .module = .phase6, .name = "zigOsvScan" },
        .zig_dependency_security_report => .{ .module = .phase6, .name = "zigDependencySecurityReport" },
        .zig_dependency_provenance => .{ .module = .phase6, .name = "zigDependencyProvenance" },
        .zig_dependency_license_summary => .{ .module = .phase6, .name = "zigDependencyLicenseSummary" },
        .zig_github_dependency_submit_plan => .{ .module = .phase6, .name = "zigGithubDependencySubmitPlan" },
        .zig_zon_dep_sync => .{ .module = .phase6, .name = "zigZonDepSync" },
        .zig_deps_add => .{ .module = .phase6, .name = "zigDepsAdd" },
        .zig_deps_remove => .{ .module = .phase6, .name = "zigDepsRemove" },
        .zig_deps_upgrade => .{ .module = .phase6, .name = "zigDepsUpgrade" },
        .zig_pkg_search => .{ .module = .phase6, .name = "zigPkgSearch" },
        .zig_pkg_info => .{ .module = .phase6, .name = "zigPkgInfo" },
        .zig_pkg_versions => .{ .module = .phase6, .name = "zigPkgVersions" },
        .zig_pkg_readme => .{ .module = .phase6, .name = "zigPkgReadme" },
        .zig_dependency_migrate => .{ .module = .phase6, .name = "zigDependencyMigrate" },
        .zig_profile_plan => .{ .module = .profiling, .name = "zigProfilePlan" },
        .zig_profile_run => .{ .module = .profiling, .name = "zigProfileRun" },
        .zig_flamegraph => .{ .module = .profiling, .name = "zigFlamegraph" },
        .zig_flamegraph_diff => .{ .module = .profiling, .name = "zigFlamegraphDiff" },
        .zigars_job_start => .{ .module = .runtime_ux, .name = "zigarsJobStart" },
        .zigars_job_status => .{ .module = .runtime_ux, .name = "zigarsJobStatus" },
        .zigars_job_result => .{ .module = .runtime_ux, .name = "zigarsJobResult" },
        .zigars_job_cancel => .{ .module = .runtime_ux, .name = "zigarsJobCancel" },
        .zigars_cancel_status => .{ .module = .runtime_ux, .name = "zigarsCancelStatus" },
        .zigars_run_stream => .{ .module = .runtime_ux, .name = "zigarsRunStream" },
        .zigars_run_events => .{ .module = .runtime_ux, .name = "zigarsRunEvents" },
        .zigars_resource_query => .{ .module = .runtime_ux, .name = "zigarsResourceQuery" },
        .zigars_resource_subscribe => .{ .module = .runtime_ux, .name = "zigarsResourceSubscribe" },
        .zigars_resource_unsubscribe => .{ .module = .runtime_ux, .name = "zigarsResourceUnsubscribe" },
        .zigars_roots_sync => .{ .module = .runtime_ux, .name = "zigarsRootsSync" },
        .zigars_workspace_map => .{ .module = .runtime_ux, .name = "zigarsWorkspaceMap" },
        .zigars_workspace_select => .{ .module = .runtime_ux, .name = "zigarsWorkspaceSelect" },
        .zigars_agent_guide_v2 => .{ .module = .runtime_ux, .name = "zigarsAgentGuideV2" },
        .zigars_client_guide => .{ .module = .runtime_ux, .name = "zigarsClientGuide" },
        .zigars_prompt_pack => .{ .module = .runtime_ux, .name = "zigarsPromptPack" },
        .zig_import_graph => .{ .module = .static_analysis, .name = "zigImportGraph" },
        .zig_import_graph_json => .{ .module = .static_analysis, .name = "zigImportGraphJson" },
        .zig_import_cycles => .{ .module = .static_analysis, .name = "zigImportCycles" },
        .zig_ast_imports => .{ .module = .static_analysis, .name = "zigAstImports" },
        .zig_decl_summary => .{ .module = .static_analysis, .name = "zigDeclSummary" },
        .zig_decl_summary_json => .{ .module = .static_analysis, .name = "zigDeclSummaryJson" },
        .zig_ast_decl_summary => .{ .module = .static_analysis, .name = "zigAstDeclSummary" },
        .zig_allocations => .{ .module = .static_analysis, .name = "zigAllocations" },
        .zig_error_sets => .{ .module = .static_analysis, .name = "zigErrorSets" },
        .zig_public_api => .{ .module = .static_analysis, .name = "zigPublicApi" },
        .zig_dead_decl_candidates => .{ .module = .static_analysis, .name = "zigDeadDeclCandidates" },
        .zig_build_graph => .{ .module = .static_analysis, .name = "zigBuildGraph" },
        .zig_build_targets => .{ .module = .static_analysis, .name = "zigBuildTargets" },
        .zig_build_options => .{ .module = .static_analysis, .name = "zigBuildOptions" },
        .zig_file_owner => .{ .module = .static_analysis, .name = "zigFileOwner" },
        .zig_import_resolve => .{ .module = .static_analysis, .name = "zigImportResolve" },
        .zig_test_discover => .{ .module = .static_analysis, .name = "zigTestDiscover" },
        .zig_ast_tests => .{ .module = .static_analysis, .name = "zigAstTests" },
        .zig_test_name_resolve => .{ .module = .static_analysis, .name = "zigTestNameResolve" },
        .zig_test_fixture_inventory => .{ .module = .static_analysis, .name = "zigTestFixtureInventory" },
        .zig_safety_site_catalog => .{ .module = .static_analysis, .name = "zigSafetySiteCatalog" },
        .zig_test_for_symbol => .{ .module = .static_analysis, .name = "zigTestForSymbol" },
        .zig_module_surface => .{ .module = .static_analysis, .name = "zigModuleSurface" },
        .zig_symbol_dossier => .{ .module = .static_analysis, .name = "zigSymbolDossier" },
        .zig_change_risk_audit => .{ .module = .static_analysis, .name = "zigChangeRiskAudit" },
        .zig_insertion_sites => .{ .module = .static_analysis, .name = "zigInsertionSites" },
        .zig_io_migration_scan => .{ .module = .static_analysis, .name = "zigIoMigrationScan" },
        .zig_leak_triage => .{ .module = .static_analysis, .name = "zigLeakTriage" },
        .zig_comptime_diagnose => .{ .module = .static_analysis, .name = "zigComptimeDiagnose" },
        .zig_memory_layout => .{ .module = .static_analysis, .name = "zigMemoryLayout" },
        .zig_unsafe_operations_audit => .{ .module = .static_analysis, .name = "zigUnsafeOperationsAudit" },
        .zig_abi_layout_diff => .{ .module = .static_analysis, .name = "zigAbiLayoutDiff" },
        .zig_changed_files_plan => .{ .module = .static_analysis, .name = "zigChangedFilesPlan" },
        .zig_dependency_inspect => .{ .module = .static_analysis, .name = "zigDependencyInspect" },
        .zig_target_matrix_plan => .{ .module = .static_analysis, .name = "zigTargetMatrixPlan" },
        .zig_test_failure_triage => .{ .module = .static_analysis, .name = "zigTestFailureTriage" },
        .zig_workspace_symbol_cache => .{ .module = .static_analysis, .name = "zigWorkspaceSymbolCache" },
        .zig_package_cache_doctor => .{ .module = .static_analysis, .name = "zigPackageCacheDoctor" },
        .zig_test_map => .{ .module = .static_analysis, .name = "zigTestMap" },
        .zig_test_select => .{ .module = .static_analysis, .name = "zigTestSelect" },
        .zig_public_api_diff => .{ .module = .static_analysis, .name = "zigPublicApiDiff" },
        .zig_semantic_index_build => .{ .module = .static_analysis, .name = "zigSemanticIndexBuild" },
        .zig_semantic_index_status => .{ .module = .static_analysis, .name = "zigSemanticIndexStatus" },
        .zig_semantic_index_refresh => .{ .module = .static_analysis, .name = "zigSemanticIndexRefresh" },
        .zig_semantic_query => .{ .module = .static_analysis, .name = "zigSemanticQuery" },
        .zig_semantic_refs => .{ .module = .static_analysis, .name = "zigSemanticRefs" },
        .zig_semantic_decl => .{ .module = .static_analysis, .name = "zigSemanticDecl" },
        .zig_semantic_callers => .{ .module = .static_analysis, .name = "zigSemanticCallers" },
        .zig_static_fusion => .{ .module = .static_analysis, .name = "zigStaticFusion" },
        .zig_code_index_export => .{ .module = .static_analysis, .name = "zigCodeIndexExport" },
        .zig_scip_export => .{ .module = .static_analysis, .name = "zigScipExport" },
        .zig_zlint => .{ .module = .static_analysis, .name = "zigZlint" },
        .zig_zlint_sarif => .{ .module = .static_analysis, .name = "zigZlintSarif" },
        .zig_zlint_rules => .{ .module = .static_analysis, .name = "zigZlintRules" },
        .zig_zlint_fix => .{ .module = .static_analysis, .name = "zigZlintFix" },
        .zig_lint_compare => .{ .module = .static_analysis, .name = "zigLintCompare" },
        .zig_lint_profile => .{ .module = .static_analysis, .name = "zigLintProfile" },
        .zig_lint_gate => .{ .module = .static_analysis, .name = "zigLintGate" },
        .zig_lint_fix_plan => .{ .module = .static_analysis, .name = "zigLintFixPlan" },
        .zig_lint_baseline => .{ .module = .static_analysis, .name = "zigLintBaseline" },
        .zig_lint_suppressions => .{ .module = .static_analysis, .name = "zigLintSuppressions" },
        .zig_lint_trend => .{ .module = .static_analysis, .name = "zigLintTrend" },
        .zigars_patch_session_create => .{ .module = .transactional_editing, .name = "zigarsPatchSessionCreate" },
        .zigars_patch_session_preview => .{ .module = .transactional_editing, .name = "zigarsPatchSessionPreview" },
        .zigars_patch_session_apply => .{ .module = .transactional_editing, .name = "zigarsPatchSessionApply" },
        .zigars_patch_session_validate => .{ .module = .transactional_editing, .name = "zigarsPatchSessionValidate" },
        .zigars_patch_session_revert => .{ .module = .transactional_editing, .name = "zigarsPatchSessionRevert" },
        .zig_generated_file_trace => .{ .module = .transactional_editing, .name = "zigGeneratedFileTrace" },
        .zigars_edit_policy_check => .{ .module = .transactional_editing, .name = "zigarsEditPolicyCheck" },
        .zigars_generated_route => .{ .module = .transactional_editing, .name = "zigarsGeneratedRoute" },
        .zig_move_decl => .{ .module = .transactional_editing, .name = "zigMoveDecl" },
        .zig_extract_decl => .{ .module = .transactional_editing, .name = "zigExtractDecl" },
        .zig_update_imports => .{ .module = .transactional_editing, .name = "zigUpdateImports" },
        .zig_organize_imports => .{ .module = .transactional_editing, .name = "zigOrganizeImports" },
        .zig_code_action_batch => .{ .module = .transactional_editing, .name = "zigCodeActionBatch" },
        .zig_impact_semantic => .{ .module = .validation_workflows, .name = "zigImpactSemantic" },
        .zig_test_select_semantic => .{ .module = .validation_workflows, .name = "zigTestSelectSemantic" },
        .zigars_validation_plan => .{ .module = .validation_workflows, .name = "zigarsValidationPlan" },
        .zigars_validation_run => .{ .module = .validation_workflows, .name = "zigarsValidationRun" },
        .zig_build_events => .{ .module = .validation_workflows, .name = "zigBuildEvents" },
        .zig_test_events => .{ .module = .validation_workflows, .name = "zigTestEvents" },
        .zig_test_timing => .{ .module = .validation_workflows, .name = "zigTestTiming" },
        .zigars_validation_history => .{ .module = .validation_workflows, .name = "zigarsValidationHistory" },
        .zig_test_flake_history => .{ .module = .validation_workflows, .name = "zigTestFlakeHistory" },
        .zig_failure_history => .{ .module = .validation_workflows, .name = "zigFailureHistory" },
        .zigars_session_snapshot => .{ .module = .validation_workflows, .name = "zigarsSessionSnapshot" },
        .zigars_handoff_pack => .{ .module = .validation_workflows, .name = "zigarsHandoffPack" },
        .zigars_decision_record => .{ .module = .validation_workflows, .name = "zigarsDecisionRecord" },
        .zigars_project_notes => .{ .module = .validation_workflows, .name = "zigarsProjectNotes" },
        .zigars_project_memory => .{ .module = .validation_workflows, .name = "zigarsProjectMemory" },
        .zigars_capability_match => .{ .module = .validation_workflows, .name = "zigarsCapabilityMatch" },
        .zigars_tool_sequence_plan => .{ .module = .validation_workflows, .name = "zigarsToolSequencePlan" },
        .zig_document_open => .{ .module = .edit_zls, .name = "zigDocumentOpen" },
        .zig_document_change => .{ .module = .edit_zls, .name = "zigDocumentChange" },
        .zig_document_close => .{ .module = .edit_zls, .name = "zigDocumentClose" },
        .zig_document_status => .{ .module = .edit_zls, .name = "zigDocumentStatus" },
        .zig_diagnostics => .{ .module = .edit_zls_diagnostics, .name = "zigDiagnostics" },
        .zig_diagnostics_all => .{ .module = .edit_zls_diagnostics, .name = "zigDiagnosticsAll" },
        .zig_diagnostics_workspace => .{ .module = .edit_zls_diagnostics, .name = "zigDiagnosticsWorkspace" },
        .zig_hover => .{ .module = .edit_zls, .name = "zigHover" },
        .zig_definition => .{ .module = .edit_zls, .name = "zigDefinition" },
        .zig_references => .{ .module = .edit_zls, .name = "zigReferences" },
        .zig_completion => .{ .module = .edit_zls, .name = "zigCompletion" },
        .zig_signature_help => .{ .module = .edit_zls, .name = "zigSignatureHelp" },
        .zig_document_symbols => .{ .module = .edit_zls, .name = "zigDocumentSymbols" },
        .zig_workspace_symbols => .{ .module = .edit_zls, .name = "zigWorkspaceSymbols" },
        .zig_lint => .{ .module = .zwanzig, .name = "zigLint" },
        .zig_lint_sarif => .{ .module = .zwanzig, .name = "zigLintSarif" },
        .zig_lint_rules => .{ .module = .zwanzig, .name = "zigLintRules" },
        .zig_analysis_graphs => .{ .module = .zwanzig, .name = "zigAnalysisGraphs" },
    };
}
