const std = @import("std");

const Io = std.Io;
const Allocator = std.mem.Allocator;
const JsonValue = std.json.Value;
const zigar = @import("zigar");
const catalog_mod = zigar.catalog;
const tool_metadata = zigar.tool_metadata;

fn readFileAlloc(allocator: Allocator, io: Io, path: []const u8, limit: usize) ![]u8 {
    return Io.Dir.cwd().readFileAlloc(io, path, allocator, .limited(limit));
}

fn writeFile(io: Io, path: []const u8, bytes: []const u8) !void {
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = bytes });
}

fn stderrPrint(io: Io, comptime fmt: []const u8, args: anytype) !void {
    var buffer: [4096]u8 = undefined;
    var writer = Io.File.stderr().writer(io, &buffer);
    try writer.interface.print(fmt, args);
    try writer.interface.flush();
}

pub fn generate(allocator: Allocator, io: Io, args: []const []const u8) !void {
    var check = false;
    for (args) |arg| {
        if (std.mem.eql(u8, arg, "--check")) {
            check = true;
        } else {
            return error.InvalidArguments;
        }
    }

    const output_path = "docs/tool-index.generated.md";
    const parsed = try catalog_mod.parsed(allocator);
    defer parsed.deinit();

    const rendered = try renderToolIndex(allocator, parsed.value);
    defer allocator.free(rendered);

    if (check) {
        const existing_owned = readFileAlloc(allocator, io, output_path, 16 * 1024 * 1024) catch null;
        defer if (existing_owned) |existing| allocator.free(existing);
        const existing = existing_owned orelse "";
        if (!std.mem.eql(u8, existing, rendered)) {
            try stderrPrint(io, "{s} is stale; run `zig build tool-index`\n", .{output_path});
            return error.StaleGeneratedFile;
        }
        return;
    }

    try writeFile(io, output_path, rendered);
}

fn renderToolIndex(allocator: Allocator, catalog: JsonValue) ![]u8 {
    const obj = catalog.object;
    var out: Io.Writer.Allocating = .init(allocator);
    errdefer out.deinit();

    try out.writer.print(
        \\# Zigar Tool Index
        \\
        \\<!-- Generated by zigar-tools generate-tool-index. Do not edit by hand. -->
        \\
        \\Schema version: `{d}`
        \\
        \\{s}
        \\
        \\## Groups
        \\
        \\
    , .{
        obj.get("schema_version").?.integer,
        obj.get("purpose").?.string,
    });

    for (obj.get("groups").?.array.items) |group_value| {
        const group = group_value.object;
        try out.writer.print("### {s}\n\nTools: ", .{group.get("name").?.string});
        try renderBacktickList(&out.writer, group.get("tools").?.array.items);
        try out.writer.writeAll("\n\nKeywords: ");
        try renderBacktickList(&out.writer, group.get("keywords").?.array.items);
        try out.writer.writeAll("\n\n");
    }

    try out.writer.writeAll("## Common Intents\n\n");
    for (obj.get("common_intents").?.array.items) |intent_value| {
        const item = intent_value.object;
        try out.writer.print("- {s}: prefer `{s}`\n", .{
            item.get("intent").?.string,
            item.get("prefer").?.string,
        });
    }
    try out.writer.writeAll("\n## Compact Argument Hints\n\n");

    var keys: std.ArrayList([]const u8) = .empty;
    defer keys.deinit(allocator);
    for (tool_metadata.specs) |spec| {
        if (spec.input_schema.fields.len > 0) try keys.append(allocator, spec.name);
    }
    std.mem.sort([]const u8, keys.items, {}, stringLessThan);

    for (keys.items) |tool_name| {
        const spec = tool_metadata.find(tool_name).?;
        try out.writer.print("- `{s}`: ", .{tool_name});
        var wrote_fragment = false;
        if (hasSchemaFields(spec, true)) {
            try out.writer.writeAll("required ");
            try renderArgumentFields(&out.writer, spec, true);
            wrote_fragment = true;
        }
        if (hasSchemaFields(spec, false)) {
            if (wrote_fragment) try out.writer.writeAll("; ");
            try out.writer.writeAll("optional ");
            try renderArgumentFields(&out.writer, spec, false);
        }
        try out.writer.writeAll("\n");
    }

    try out.writer.print("\n{s}\n", .{obj.get("tools_list_schema_note").?.string});
    return try out.toOwnedSlice();
}

fn stringLessThan(_: void, lhs: []const u8, rhs: []const u8) bool {
    return std.mem.order(u8, lhs, rhs) == .lt;
}

fn renderBacktickList(writer: *Io.Writer, items: []const JsonValue) !void {
    for (items, 0..) |item, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{item.string});
    }
}

fn hasSchemaFields(spec: tool_metadata.ToolMeta, required: bool) bool {
    for (spec.input_schema.fields) |field| {
        if (field[2] == required) return true;
    }
    return false;
}

fn renderArgumentFields(writer: *Io.Writer, spec: tool_metadata.ToolMeta, required: bool) !void {
    var i: usize = 0;
    for (spec.input_schema.fields) |field| {
        if (field[2] != required) continue;
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}: {s}`", .{ field[0], field[1] });
        i += 1;
    }
}
